// Static mock data for the transactions list and detail pages

export const transactions = [
  {
    id: 'd6f6e5c5-a724-4bfa-985b-2d6ff8829a08',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Success',
    documentType: 'INV',
    status: 'Exported',
    processedDate: '20/04/2026 09:44:00',
    exportedDate: '20/04/2026 09:44:01',
    sender: 'Front End Test',
    transactionNumber: 'FES8T101-INVS8T1D1',
    orderNumber: 'FES8T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-7t101',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Success',
    documentType: 'INV',
    status: 'Exported',
    processedDate: '20/04/2026 09:42:25',
    exportedDate: '20/04/2026 09:42:26',
    sender: 'Front End Test',
    transactionNumber: 'FES7T101-INVS7T1D1',
    orderNumber: 'FES7T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-9t101',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Invalid Order Number',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:54',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES9T101-INVS9T1D1',
    orderNumber: 'FES9T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'Release Testing - Front End',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-10t101',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Failed to capture data',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:54',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES10T101-INVS10T1D1',
    orderNumber: 'FES10T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-5t101',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Failed to capture data',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:50',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES5T101-INVS5T1D1',
    orderNumber: 'FES5T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-6t101',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Failed to capture data',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:50',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES6T101-INVS6T1D1',
    orderNumber: 'FES6T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-2t101-d3',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Failed to capture data',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:46',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES2T101-INVS2T1D3',
    orderNumber: 'FES2T101',
    transactionDate: '06/10/2022',
    net: '50.00',
    vat: '0.00',
    total: '50.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-2t101-d2',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Failed to capture data',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:45',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES2T101-INVS2T1D2',
    orderNumber: 'FES2T101',
    transactionDate: '06/10/2022',
    net: '50.00',
    vat: '0.00',
    total: '50.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-3t101',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Failed to capture data',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:44',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES3T101-INVS3T1D1',
    orderNumber: 'FES3T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  },
  {
    id: 'tx-1t101',
    type: 'INV',
    group: 'Release Testing - Front End',
    reason: 'Failed to capture data',
    documentType: 'INV',
    status: 'Suspended',
    processedDate: '20/04/2026 09:10:44',
    exportedDate: '',
    sender: 'Front End Test',
    transactionNumber: 'FES1T101-INVS1T1D1',
    orderNumber: 'FES1T101',
    transactionDate: '06/10/2022',
    net: '150.00',
    vat: '0.00',
    total: '150.00',
    assignedTo: 'OpenECX Admin',
    customerName: 'Release Testing - Front End',
    engine: 0
  }
];

// Detail page content for a single transaction
export const transactionDetail = {
  id: 'd6f6e5c5-a724-4bfa-985b-2d6ff8829a08',
  breadcrumb: ['Transactions', 'Sales Invoice'],
  details: {
    Engine: 'Rule Engine',
    Workflow: 'FES8T1',
    Reason: 'Success',
    Sender: 'Front End Test',
    'Invoice Number': 'FES8T101-INVS8T1D1',
    'Order Number': 'FES8T101',
    Processed: '20/04/2026 09:44:00',
    'Invoice Date': '06/10/2022',
    Status: 'Exported',
    'Tax Date': '',
    'Delivery Date': '',
    'Due Date': '',
    'Delivery From': '',
    'Delivery Note Number': '',
    'Delivery Note Reference': '',
    Contract: '',
    "Supplier's Order": '',
    'Supplier Tax Number': 'Test VAT number',
    'Type of Supply': '',
    'Original Invoice Number': '',
    'Original Invoice Date': '',
    'Original Order Date': '',
    'Reason for Credit': '',
    Notes: '',
    'Payment Terms': '',
    'Processed Time In Seconds': '2006.2966009'
  },
  documents: [
    { label: 'Source File', view: true, download: true },
    { label: 'Extracted Text (Page 1)', view: true, download: true },
    { label: 'Transaction Document', view: true, download: true },
    { label: 'Export File (FES8T101.xml)', view: true, download: true },
    { label: 'Data Output', view: false, download: true },
    { label: 'More', send: true }
  ],
  attachments: [
    'fes1t101-invs1t1d1.pdf',
    'fes2t101-invs2t1d1-3.pdf',
    'fes3t101-invs3t1d1.pdf',
    'fes4t101-invs4t1d1.pdf',
    'fes5t101-invs5t1d1.pdf',
    'fes6t101-invs6t1d1.pdf',
    'fes7t101-invs7t1d1.pdf',
    'fes8t101-invs8t1d1.pdf',
    'fes9t101-invs9t1d1.pdf',
    'fes10t101-invs10t1d1.pdf'
  ],
  lineItems: [
    {
      line: 1,
      supplierCode: 'FES8T1-1',
      buyerCode: '',
      description: 'S8 – Test 1 – Product 1',
      quantity: '5.00',
      price: '10.00',
      discountPct: '0.00',
      discountAmount: '0.00',
      vatRate: '0.00',
      vatAmount: '0.00',
      netAmount: '50.00',
      total: '50.00'
    },
    {
      line: 2,
      supplierCode: 'FES8T1-2',
      buyerCode: '',
      description: 'S8 – Test 1 – Product 2',
      quantity: '5.00',
      price: '10.00',
      discountPct: '0.00',
      discountAmount: '0.00',
      vatRate: '0.00',
      vatAmount: '0.00',
      netAmount: '50.00',
      total: '50.00'
    },
    {
      line: 3,
      supplierCode: 'FES8T1-3',
      buyerCode: '',
      description: 'S8 – Test 1 – Product 3',
      quantity: '5.00',
      price: '10.00',
      discountPct: '0.00',
      discountAmount: '0.00',
      vatRate: '0.00',
      vatAmount: '0.00',
      netAmount: '50.00',
      total: '50.00'
    }
  ],
  totals: {
    discountAmount: '0.00',
    vatAmount: '0.00',
    netAmount: '150.00',
    total: '150.00'
  }
};

// Customers shown in the filter pane
export const customers = [
  'Adama',
  'AI Test Customer',
  'Aptus Utilities',
  'austin 2',
  'Boulder Developments',
  'Bright Star Ltd',
  'Cheetham Mills',
  'Chen & Co',
  'DataForge',
  'Delta Shipping',
  'EnerTech',
  'Finley Foods'
];
